name: OrigPowers
version: 1.0
main: pink.rat.Powers.Application
api-version: 1.21.4
load: STARTUP

commands:
   setpower:
      description: Sets your current power.
      usage: /setpower <name>
   power:
      description: Gets your current power.
      usage: /power